# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  VERSION: 0.0.1
  JUMBLE_IMAGE: localhost/hamidoujand/jumble:{{.VERSION}}

tasks:
  tidy:
    silent: true
    cmds:
      - go mod tidy
      - go mod vendor
  run:
    cmds:
      - go run cmd/main.go
    silent: true

  build:
    cmds:
      - task: jumble

  jumble:
    silent: true
    cmds:
      - docker buildx build
        -f infra/docker/jumble.dockerfile
        -t {{.JUMBLE_IMAGE}}
        --build-arg BUILD={{.VERSION}}
        --build-arg CREATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        --load
        .

  apply:
    silent: true
    cmds:
      - kubectl apply -f infra/k8s/base/namespace.yml
      - kubectl apply -f infra/k8s/tempo/tempo.yml
      - kubectl apply -f infra/k8s/jumble/jumble-conf.yml
      - kubectl apply -f infra/k8s/jumble/jumble-secret.yml
      - kubectl apply -f infra/k8s/database/database.yml
      - kubectl rollout status --namespace=jumble-system --watch --timeout=120s sts/database
      - kubectl apply -f infra/k8s/jumble/jumble-depl.yml
      - kubectl rollout status --namespace=jumble-system --watch --timeout=120s deployment/jumble

  delete:
    silent: true
    cmds:
      - kubectl delete -f infra/k8s/jumble/jumble-depl.yml
      - kubectl delete -f infra/k8s/tempo/tempo.yml
      - kubectl delete -f infra/k8s/database/database.yml
      - kubectl delete -f infra/k8s/jumble/jumble-conf.yml
      - kubectl delete -f infra/k8s/jumble/jumble-secret.yml
      - kubectl delete -f infra/k8s/base/namespace.yml

  logs:
    silent: true
    # if you have more than 1 pods, the "-l=app=jumble" matches all of them, and --max-log-requests=6 only fetches logs from 6 of
    # those replicas in one batch to not put a lot of pressure on system.
    cmd: kubectl logs --namespace=jumble-system -l=app=jumble --all-containers=true -f --tail=100 --max-log-requests=6

  logs-db:
    silent: true
    cmd: kubectl logs --namespace=jumble-system -l app=database --all-containers=true -f --tail=100

  logs-tempo:
    silent: true
    cmd: kubectl logs --namespace=jumble-system -l app=tempo --all-containers=true -f --tail=100

  restart:
    silent: true
    cmds:
      - kubectl rollout restart deployment jumble --namespace=jumble-system

  restart-db:
    silent: true
    cmd: kubectl rollout restart statefulset database --namespace=jumble-system

  status:
    silent: true
    cmds:
      # watch executes the next command every 2 seconds to get updated list
      - watch -n 2 kubectl get pods -o wide --namespace=jumble-system

  describe-depl:
    silent: true
    cmd: kubectl describe deployment --namespace=jumble-system jumble

  describe-jumble:
    silent: true
    cmd: kubectl describe pod --namespace=jumble-system -l app=jumble

  describe-database:
    silent: true
    cmd: kubectl describe pod --namespace=jumble-system -l app=database

  service:
    silent: true
    cmd: kubectl port-forward service/jumble-service 8000:8000 --namespace=jumble-system

  load:
    silent: true
    cmd: hey -m GET -c 100 -n 10000 http://localhost:8000/v1/users

  metrics:
    silent: true
    cmd: expvarmon -ports="localhost:3000" -endpoint="/debug/vars" -vars="build,requests,goroutines,errors,panics,mem:memstats.HeapAlloc,mem:memstats.HeapSys,mem:memstats.Sys"

  genkey:
    silent: true
    cmds:
      # generate private key
      - openssl genrsa -out infra/keys/private.pem 2048
      # extract public key from private key
      - openssl rsa -in infra/keys/private.pem -pubout -out infra/keys/public.pem
