# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  VERSION: 0.0.1
  JUMBLE_IMAGE: localhost/hamidoujand/jumble:{{.VERSION}}

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  run:
    cmds:
      - go run cmd/main.go
    silent: true

  build:
    cmds:
      - task: jumble

  jumble:
    silent: true
    cmds:
      - docker buildx build
        -f infra/docker/jumble.dockerfile
        -t {{.JUMBLE_IMAGE}}
        --build-arg BUILD={{.VERSION}}
        --build-arg CREATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        --load
        .
  apply:
    silent: true
    cmds:
      - kubectl apply -f infra/k8s/jumble/jumble-depl.yml
  delete:
    silent: true
    cmds:
      - kubectl delete -f infra/k8s/jumble/jumble-depl.yml
  logs:
    silent: true
    # if you have more than 1 pods, the "-l=app=jumble" matches all of them, and --max-log-requests=6 only fetches logs from 6 of
    # those replicas in one batch to not put a lot of pressure on system.
    cmd: kubectl logs --namespace=jumble-system -l=app=jumble --all-containers=true -f --tail=100 --max-log-requests=6

  restart:
    silent: true
    cmds:
      - kubectl rollout restart deployment jumble --namespace=jumble-system

  status:
    silent: true
    cmds:
      # watch executes the next command every 2 seconds to get updated list
      - watch -n 2 kubectl get pods -o wide --namespace=jumble-system

  describe-depl:
    silent: true
    cmd: kubectl describe deployment --namespace=jumble-system jumble

  describe-jumble:
    silent: true
    cmd: kubectl describe pod --namespace=jumble-system -l app=jumble
