apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-conf
  namespace: jumble-system

data:
  tempo.yml: |
    usage_report:
     reporting_enabled: false         #do not send any data back to grafana-labs.
    server:
     http_listen_port: 3200    # main port that tempo runs on

    distributor: # how Tempo receives trace data from various sources
      receivers: 
        otlp:
          protocols:
            http:
              endpoint: "tempo:4318"
            grpc:
              endpoint: "tempo:4317"

    # responsible for processing and batching trace data before writing it to storage
    ingester:
      trace_idle_period: 10s               # waits 10s and if no span received it considers the trace as complete as writes it to store
      max_block_bytes: 1_000_000           # Creates a new storage block when the current block reaches ~1MB
      max_block_duration: 5m               # Forces a block to be flushed every 5 minutes, regardless of size

    # compactor component is responsible for optimizing storage by merging smaller blocks into larger, more efficient blocks.
    compactor:
      compaction:
        compaction_window: 1h              # blocks in this time window will be compacted together
        max_block_bytes: 100_000_000       # maximum size of compacted blocks
        block_retention: 1h                # Keeps original (uncompacted) blocks for 1 hour after compaction
        compacted_block_retention: 10m     # Keeps compacted blocks for an additional 10 minutes Ensures data is available during the compaction process


    # configures Tempo's storage layer, which handles how trace data is stored, indexed, and retrieved.
    storage:
      trace:
        backend: local                     # Stores all trace data on the local filesystem good for dev.
        block:
          bloom_filter_false_positive: .05   # Bloom filters quickly check if a trace ID might exist in a block
          v2_index_downsample_bytes: 1000     # Creates an index entry every 1000 bytes of trace data
          v2_encoding: zstd                   # Excellent compression/performance balance 
        wal:
          path: /tmp/tempo/wal             # where to store the the wal locally
          v2_encoding: snappy              # WAL needs fast writes, not maximum compression so snappy it good
        local:
          path: /tmp/tempo/blocks         # Stores final block data in /tmp/tempo/blocks
        pool:
          max_workers: 100                 # Allows up to 100 concurrent storage operations Parallel reads/writes to the storage backend
          queue_depth: 10000               # Queue up to 10,000 storage operations when all workers are busy

    #configures Tempo's metrics generation capabilities
    overrides:
      metrics_generator_processors: [ service-graphs, span-metrics ]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: jumble-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 0 # Don't keep any old ReplicaSets after an update
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      namespace: jumble-system
      labels:
        app: tempo
    spec:
      hostname: tempo
      containers:
        - image: grafana/tempo:2.8.1
          name: tempo
          ports:
            - containerPort: 14268
              hostPort: 14268
            - containerPort: 3200
              hostPort: 3200
            - containerPort: 4317
              hostPort: 4317
            - containerPort: 4318
              hostPort: 4318
            - containerPort: 9411
              hostPort: 9411
          args:
            - -config.file=/tempo-conf/tempo.yml
          volumeMounts:
            - name: config-volume
              mountPath: /tempo-conf
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: config-volume
          configMap:
            name: tempo-conf

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: jumble-system
spec:
  type: ClusterIP
  selector:
    app: tempo
  ports:
    - port: 14268
      name: "14268"
    - port: 3200
      name: "3200"
    - port: 4317
      name: "4317"
    - port: 4318
      name: "4318"
    - port: 9411
      name: "9411"
