apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: jumble-system
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo
        pool:
          max_workers: 100
          queue_depth: 10000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: jumble-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 0 # Don't keep any old ReplicaSets after an update
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      namespace: jumble-system
      labels:
        app: tempo
    spec:
      hostname: tempo
      containers:
        - image: grafana/tempo:2.8.1
          name: tempo
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          args: ["-config.file=/etc/tempo/tempo.yaml"]
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
            - name: tempo-storage
              mountPath: /var/tempo
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: jumble-system
spec:
  selector:
    app: tempo
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
