apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: database-data
  namespace: jumble-system

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: database
  namespace: jumble-system

spec:
  selector:
    matchLabels:
      app: database

  serviceName: database-service
  replicas: 1
  template:
    metadata:
      labels:
        app: database

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: database-data

      containers:
        - name: postgres
          image: postgres:16.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          env:
            - name: POSTGRES_PASSWORD
              value: postgres

          ports:
            - containerPort: 5432
              name: postgres
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 60
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: jumble-system
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
