apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3100
    access: proxy
    isDefault: true
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
